package net.iessochoa.pmdm.t11_ejemplointents.ui.navigation

import kotlinx.serialization.Serializable

@Serializable
object IntentsAndPermissionsScreenDestination

@Serializable
object PermisosScreenDestination

@Serializable
object PermisosLibreriaScreenDestination

@Serializable
object PermisosLibreriaSolicitudInmediataScreenDestination

@Serializable
object NavigationDrawerScreenDestination
